# Generated by Django 5.1.7 on 2025-05-10 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0002_remove_chart_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='share_token',
        ),
    ]
