# Generated by Django 5.1.7 on 2025-05-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0003_remove_dashboard_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='layout_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
