# Generated by Django 5.1.7 on 2025-05-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0004_dashboard_layout_json'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
